### ISSUE TITLE
question

### ISSUE THREAD

**Issue by lichacha** [junqiangchen/VNet#1]
Hi, I have two questions.
1: I didn't see your trained model. Just like the file of *.pd. My gpu is estimated to train for many days.
2: What is the content of your CSV file? or likle
E:\project\VNet-master\train\Case00.mhd
E:\project\VNet-master\train\Case01.mhd
E:\project\VNet-master\train\Case02.mhd

Thank you for your work

**Comment by junqiangchen** [comment]
Hi,i am very happy with your question.
the first question,trained Vnet model is very big, almost 150M,i will share the best trained model on Baidu cloud disk.
the second question,the csv file is the format like this:
D:\Data\PROMISE2012\Augmentation\Image/0_1.bmp
D:\Data\PROMISE2012\Augmentation\Image/0_10.bmp
D:\Data\PROMISE2012\Augmentation\Image/0_2.bmp

i convert the source data with mhd into bmp format,and i also augment the data with geometric transformation，i also attach the trained data on Baidu cloud disk.

**Comment by lichacha** [comment]
Can you provide data-enhanced code? thank you
