### ISSUE TITLE
关于数据预处理

### ISSUE THREAD

**Issue by shiontao** [junqiangchen/VNet#3]
我看到你的原始图像处理的很好,能否提供预处理程序

**Comment by junqiangchen** [comment]
图像预处理过程其实没那么复杂，就是将原始图像做了一下0-255的映射变换。

**Comment by shiontao** [comment]
> 图像预处理过程其实没那么复杂，就是将原始图像做了一下0-255的映射变换。

是这样啊,我看到你展示的mri图像亮度很均衡,以为是做了其他处理

**Comment by junqiangchen** [comment]
有些case如果对比度不高的可以做一下直方图均衡化处理
